meta_product_name: "Substracked"
meta_title: "Substracked - The Online Subscription Manager"
meta_description: "Substracked is an online subscription management system designed to prevent you from losing money on unwanted subscriptions."
meta_image: "cover.png"
